local ROOT=assert(arg[1]);local f=assert(io.open(ROOT..'/source/client/palcraft-collisions.lua','rb'));local s=f:read('*a');f:close()
local first=s:sub(assert(s:find('local world_observers',1,true)),assert(s:find('M.context=context',1,true))-1)
local second=s:sub(assert(s:find('local function observe(method,',1,true)),assert(s:find('local World=dofile',1,true))-1)
local abandon=s:sub(assert(s:find('function M.abandon()',1,true)),assert(s:find('local tick',s:find('function M.abandon()',1,true),true))-1)
local api=assert(load('local M={}\n'..first..second..abandon..'\nreturn{set=M.set_world_observer,observe=observe,state=M,abandon=M.abandon}'))()
local checks=0;local function ck(x,m)checks=checks+1;assert(x,m)end
local a,b=0,0;api.set({on_row=function()a=a+1 end});api.set({on_row=function()b=b+1 end},'server')
api.observe('on_row',{},true);ck(a==1 and b==1,'One accepted reducer row dispatches once per owner')
api.set({on_row=function()b=b+1 end},'server');api.observe('on_row',{},true);ck(a==2 and b==2,'Same owner replacement does not duplicate callback')
api.set(nil,'server');api.observe('on_row',{},true);ck(a==3 and b==2,'Server stop leaves default client observer')
api.set({on_row=function()b=b+1 end},'server');api.set(nil);api.observe('on_row',{},true);ck(a==3 and b==3,'Default stop leaves separate server observer')
api.set({on_row=function()error('actual_observer_error')end},'server');api.observe('on_row',{},true);ck(api.state.observer_error:find('actual_observer_error',1,true),'Observer errors retain fail-closed error signal')
api.set({on_row=function()a=a+1 end});api.set({on_row=function()b=b+1 end},'server')
local prev_a,prev_b=a,b
api.abandon();api.observe('on_row',{},true)
ck(a==prev_a and b==prev_b,'Dead-world abandon clears default and named callbacks')
ck(api.state.world_observer==nil and api.state.abandoned,'Original dead-world single-slot state retained')
api.set({on_row=function()a=a+1 end});api.observe('on_row',{},true)
ck(a==prev_a+1 and b==prev_b,'Later default rebind cannot dispatch abandoned named realm callback')
print('PASS observer slots '..checks..' checks; actual candidate functions, no journal/timer/game')
